### ISSUE TITLE
Auf andere MVG API umstellen

### ISSUE THREAD

**Issue by Huber1** [Huber1/betterHM#89]
Die mvg api ist extrem langsam und übermittelt viel mehr daten als eigentlich benötigt werden.

=> Umstellen auf eine andere

Beispiel-Aufruf: https://www.mvg.de/api/fib/v2/departure?globalId=de:09162:79&limit=20&offsetInMinutes=0&transportTypes=UBAHN,TRAM,BUS,SBAHN,SCHIFF

**Comment by Huber1** [comment]
müsste nicht allzu viel aufwand sein. hauptsächlich updaten der data klassen

**Comment by Huber1** [comment]
fast fertig. muss die config noch bissl anpassen

**Comment by Huber1** [comment]
- closed with #95

**Comment by adriangeorgimmel** [comment]
Würde noch andere Stationen für die anderen Campus hinzufügend:
de:09162:1666	Avenariusplatz
de:09162:53		Ottostraße
de:09162:16		Lenbachplatz

**Comment by Huber1** [comment]
machst du?

**Comment by Huber1** [comment]
Sind ab Version 1.3.1 mit drin
